package com.myava.mybatis.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Database Table Remarks:
 *   邮件通知失败日志
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table email_notify_err_log
 */
@Table(name = "email_notify_err_log")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class EmailNotifyErrLog implements Serializable {
    /**
     * id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Integer id;

    /**
     * 类型
     */
    @Column(name = "type")
    private Integer type;

    /**
     * 参数类名
     */
    @Column(name = "clazz")
    private String clazz;

    /**
     * 重试次数
     */
    @Column(name = "retry_times")
    private Integer retryTimes;

    /**
     * 创建时间
     */
    @Column(name = "create_time")
    private Date createTime;

    /**
     * 更新时间
     */
    @Column(name = "update_time")
    private Date updateTime;

    /**
     * 参数Json
     */
    @Column(name = "param_json")
    private String paramJson;

    /**
     * 备注
     */
    @Column(name = "remark")
    private String remark;

    private static final long serialVersionUID = 1L;
}