server:
  port: 8888

logging:
  config: classpath:logback-spring.xml
  path: /data/logs/${spring.application.name}

spring:
  application:
    name: myava-spring-boot
  profiles:
    active: default
  datasource.druid:
    name: myava-ds
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useServerPrepStmts=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    initial-size: 1
    min-idle: 1
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 50
        max-idle: 10
        min-idle: 5
        max-wait: 6000
    timeout: 5000

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring.thymeleaf:
  enabled: true
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML5
  encoding: UTF-8
  cache: false
  servlet.content-type: text/html

#regCenter:
#  serverList: 127.0.0.1:2181
#  namespace: demo-elastic-job

# will inject 'application' namespace in bootstrap phase
#apollo.bootstrap.enabled: true
# put apollo initialization before logging system initialization
#apollo.bootstrap.eagerLoad.enabled=true

